//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Commerce.Proxy.AccountService
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractRequest", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.UpdateAccountInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.GetAccountInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.AddRoleAssignmentInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.GetPermitsForObjectIdInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.CreateAccountInput))]
    public partial class AbstractRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBagField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAccountInput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class UpdateAccountInput : Microsoft.Commerce.Proxy.AccountService.AbstractRequest
    {
        
        private Microsoft.Commerce.Proxy.AccountService.APIContext APIContextField;
        
        private Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountInputInfoField;
        
        private Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfoField;
        
        private System.Guid OnBehalfOfPartnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.APIContext APIContext
        {
            get
            {
                return this.APIContextField;
            }
            set
            {
                this.APIContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountInputInfo
        {
            get
            {
                return this.AccountInputInfoField;
            }
            set
            {
                this.AccountInputInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfo
        {
            get
            {
                return this.CallerInfoField;
            }
            set
            {
                this.CallerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OnBehalfOfPartner
        {
            get
            {
                return this.OnBehalfOfPartnerField;
            }
            set
            {
                this.OnBehalfOfPartnerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAccountInput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class GetAccountInput : Microsoft.Commerce.Proxy.AccountService.AbstractRequest
    {
        
        private Microsoft.Commerce.Proxy.AccountService.APIContext APIContextField;
        
        private Microsoft.Commerce.Proxy.AccountService.AdditionalRequiredInfo AdditionalRequiredInfoField;
        
        private bool AllAddressesReturnedField;
        
        private Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfoField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] FiltersField;
        
        private Microsoft.Commerce.Proxy.AccountService.AccountSearchCriteria SearchCriteriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.APIContext APIContext
        {
            get
            {
                return this.APIContextField;
            }
            set
            {
                this.APIContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AdditionalRequiredInfo AdditionalRequiredInfo
        {
            get
            {
                return this.AdditionalRequiredInfoField;
            }
            set
            {
                this.AdditionalRequiredInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllAddressesReturned
        {
            get
            {
                return this.AllAddressesReturnedField;
            }
            set
            {
                this.AllAddressesReturnedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfo
        {
            get
            {
                return this.CallerInfoField;
            }
            set
            {
                this.CallerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] Filters
        {
            get
            {
                return this.FiltersField;
            }
            set
            {
                this.FiltersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AccountSearchCriteria SearchCriteria
        {
            get
            {
                return this.SearchCriteriaField;
            }
            set
            {
                this.SearchCriteriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddRoleAssignmentInput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class AddRoleAssignmentInput : Microsoft.Commerce.Proxy.AccountService.AbstractRequest
    {
        
        private Microsoft.Commerce.Proxy.AccountService.APIContext APIContextField;
        
        private Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfoField;
        
        private System.Guid OnBehalfOfPartnerField;
        
        private Microsoft.Commerce.Proxy.AccountService.RoleAssignment RoleAssignmentInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.APIContext APIContext
        {
            get
            {
                return this.APIContextField;
            }
            set
            {
                this.APIContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfo
        {
            get
            {
                return this.CallerInfoField;
            }
            set
            {
                this.CallerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OnBehalfOfPartner
        {
            get
            {
                return this.OnBehalfOfPartnerField;
            }
            set
            {
                this.OnBehalfOfPartnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.RoleAssignment RoleAssignmentInput
        {
            get
            {
                return this.RoleAssignmentInputField;
            }
            set
            {
                this.RoleAssignmentInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPermitsForObjectIdInput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class GetPermitsForObjectIdInput : Microsoft.Commerce.Proxy.AccountService.AbstractRequest
    {
        
        private Microsoft.Commerce.Proxy.AccountService.APIContext APIContextField;
        
        private Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfoField;
        
        private string TargetObjectIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.APIContext APIContext
        {
            get
            {
                return this.APIContextField;
            }
            set
            {
                this.APIContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfo
        {
            get
            {
                return this.CallerInfoField;
            }
            set
            {
                this.CallerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetObjectId
        {
            get
            {
                return this.TargetObjectIdField;
            }
            set
            {
                this.TargetObjectIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAccountInput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class CreateAccountInput : Microsoft.Commerce.Proxy.AccountService.AbstractRequest
    {
        
        private Microsoft.Commerce.Proxy.AccountService.APIContext APIContextField;
        
        private Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountInputInfoField;
        
        private Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfoField;
        
        private System.Guid OnBehalfOfPartnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.APIContext APIContext
        {
            get
            {
                return this.APIContextField;
            }
            set
            {
                this.APIContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountInputInfo
        {
            get
            {
                return this.AccountInputInfoField;
            }
            set
            {
                this.AccountInputInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.CallerInfo CallerInfo
        {
            get
            {
                return this.CallerInfoField;
            }
            set
            {
                this.CallerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OnBehalfOfPartner
        {
            get
            {
                return this.OnBehalfOfPartnerField;
            }
            set
            {
                this.OnBehalfOfPartnerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string NamespaceField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namespace
        {
            get
            {
                return this.NamespaceField;
            }
            set
            {
                this.NamespaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIContext", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class APIContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] FraudDetectionContextField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBagField;
        
        private System.Guid TrackingGuidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] FraudDetectionContext
        {
            get
            {
                return this.FraudDetectionContextField;
            }
            set
            {
                this.FraudDetectionContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TrackingGuid
        {
            get
            {
                return this.TrackingGuidField;
            }
            set
            {
                this.TrackingGuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AccountIDField;
        
        private string AccountLevelField;
        
        private string AccountRoleField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] CustomPropertiesField;
        
        private Microsoft.Commerce.Proxy.AccountService.PayinAccountInfo PayinInfoField;
        
        private Microsoft.Commerce.Proxy.AccountService.PayoutAccountInfo PayoutInfoField;
        
        private Microsoft.Commerce.Proxy.AccountService.TaxProfileInfo[] TaxProfilesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountLevel
        {
            get
            {
                return this.AccountLevelField;
            }
            set
            {
                this.AccountLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountRole
        {
            get
            {
                return this.AccountRoleField;
            }
            set
            {
                this.AccountRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] CustomProperties
        {
            get
            {
                return this.CustomPropertiesField;
            }
            set
            {
                this.CustomPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.PayinAccountInfo PayinInfo
        {
            get
            {
                return this.PayinInfoField;
            }
            set
            {
                this.PayinInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.PayoutAccountInfo PayoutInfo
        {
            get
            {
                return this.PayoutInfoField;
            }
            set
            {
                this.PayoutInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.TaxProfileInfo[] TaxProfiles
        {
            get
            {
                return this.TaxProfilesField;
            }
            set
            {
                this.TaxProfilesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallerInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class CallerInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AccountIdField;
        
        private Microsoft.Commerce.Proxy.AccountService.Identity DelegatorField;
        
        private Microsoft.Commerce.Proxy.AccountService.Identity RequesterField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                this.AccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Identity Delegator
        {
            get
            {
                return this.DelegatorField;
            }
            set
            {
                this.DelegatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Identity Requester
        {
            get
            {
                return this.RequesterField;
            }
            set
            {
                this.RequesterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayinAccountInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class PayinAccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Commerce.Proxy.AccountService.Address[] AddressSetField;
        
        private int AnniversaryDateField;
        
        private string CompanyNameField;
        
        private string CompanyNamePronunciationField;
        
        private Microsoft.Commerce.Proxy.AccountService.Address CorporateAddressField;
        
        private string CorporateIdentityField;
        
        private string CorporateLegalEntityField;
        
        private string CorporateVatIdField;
        
        private string CountryCodeField;
        
        private System.DateTime CreatedDateField;
        
        private string CurrencyField;
        
        private System.Nullable<Microsoft.Commerce.Proxy.AccountService.CustomerType> CustomerTypeField;
        
        private string DefaultAddressIDField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string FirstNamePronunciationField;
        
        private string FriendlyNameField;
        
        private string HCIField;
        
        private string HCIValidField;
        
        private System.DateTime HistoryDateField;
        
        private string LastNameField;
        
        private string LastNamePronunciationField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string LocaleField;
        
        private Microsoft.Commerce.Proxy.AccountService.Phone[] PhoneSetField;
        
        private System.Nullable<Microsoft.Commerce.Proxy.AccountService.AccountStatus> StatusField;
        
        private Microsoft.Commerce.Proxy.AccountService.TaxExemptionInfo[] TaxExemptionInfoSetField;
        
        private Microsoft.Commerce.Proxy.AccountService.Violation[] ViolationsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Address[] AddressSet
        {
            get
            {
                return this.AddressSetField;
            }
            set
            {
                this.AddressSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnniversaryDate
        {
            get
            {
                return this.AnniversaryDateField;
            }
            set
            {
                this.AnniversaryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyNamePronunciation
        {
            get
            {
                return this.CompanyNamePronunciationField;
            }
            set
            {
                this.CompanyNamePronunciationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Address CorporateAddress
        {
            get
            {
                return this.CorporateAddressField;
            }
            set
            {
                this.CorporateAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorporateIdentity
        {
            get
            {
                return this.CorporateIdentityField;
            }
            set
            {
                this.CorporateIdentityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorporateLegalEntity
        {
            get
            {
                return this.CorporateLegalEntityField;
            }
            set
            {
                this.CorporateLegalEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorporateVatId
        {
            get
            {
                return this.CorporateVatIdField;
            }
            set
            {
                this.CorporateVatIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Microsoft.Commerce.Proxy.AccountService.CustomerType> CustomerType
        {
            get
            {
                return this.CustomerTypeField;
            }
            set
            {
                this.CustomerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultAddressID
        {
            get
            {
                return this.DefaultAddressIDField;
            }
            set
            {
                this.DefaultAddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNamePronunciation
        {
            get
            {
                return this.FirstNamePronunciationField;
            }
            set
            {
                this.FirstNamePronunciationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCI
        {
            get
            {
                return this.HCIField;
            }
            set
            {
                this.HCIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCIValid
        {
            get
            {
                return this.HCIValidField;
            }
            set
            {
                this.HCIValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HistoryDate
        {
            get
            {
                return this.HistoryDateField;
            }
            set
            {
                this.HistoryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNamePronunciation
        {
            get
            {
                return this.LastNamePronunciationField;
            }
            set
            {
                this.LastNamePronunciationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale
        {
            get
            {
                return this.LocaleField;
            }
            set
            {
                this.LocaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Phone[] PhoneSet
        {
            get
            {
                return this.PhoneSetField;
            }
            set
            {
                this.PhoneSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Microsoft.Commerce.Proxy.AccountService.AccountStatus> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.TaxExemptionInfo[] TaxExemptionInfoSet
        {
            get
            {
                return this.TaxExemptionInfoSetField;
            }
            set
            {
                this.TaxExemptionInfoSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Violation[] Violations
        {
            get
            {
                return this.ViolationsField;
            }
            set
            {
                this.ViolationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayoutAccountInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class PayoutAccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AnniversaryDateField;
        
        private string CountryCodeField;
        
        private System.DateTime CreatedDateField;
        
        private string CurrencyField;
        
        private string EmailField;
        
        private string FriendlyNameField;
        
        private System.DateTime LastUpdatedDateField;
        
        private string LocaleField;
        
        private System.Nullable<Microsoft.Commerce.Proxy.AccountService.AccountStatus> StatusField;
        
        private Microsoft.Commerce.Proxy.AccountService.Violation[] ViolationsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnniversaryDate
        {
            get
            {
                return this.AnniversaryDateField;
            }
            set
            {
                this.AnniversaryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate
        {
            get
            {
                return this.LastUpdatedDateField;
            }
            set
            {
                this.LastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale
        {
            get
            {
                return this.LocaleField;
            }
            set
            {
                this.LocaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Microsoft.Commerce.Proxy.AccountService.AccountStatus> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Violation[] Violations
        {
            get
            {
                return this.ViolationsField;
            }
            set
            {
                this.ViolationsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxProfileInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class TaxProfileInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressIDField;
        
        private string CityField;
        
        private string CountryCodeField;
        
        private string DistrictField;
        
        private string FirstNameField;
        
        private string FriendlyNameField;
        
        private string LastNameField;
        
        private Microsoft.Commerce.Proxy.AccountService.MapAddressResult MapAddressResultField;
        
        private string PostalCodeField;
        
        private string StateField;
        
        private string Street1Field;
        
        private string Street2Field;
        
        private string Street3Field;
        
        private string UnitNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressID
        {
            get
            {
                return this.AddressIDField;
            }
            set
            {
                this.AddressIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.MapAddressResult MapAddressResult
        {
            get
            {
                return this.MapAddressResultField;
            }
            set
            {
                this.MapAddressResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street1
        {
            get
            {
                return this.Street1Field;
            }
            set
            {
                this.Street1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street2
        {
            get
            {
                return this.Street2Field;
            }
            set
            {
                this.Street2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street3
        {
            get
            {
                return this.Street3Field;
            }
            set
            {
                this.Street3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNumber
        {
            get
            {
                return this.UnitNumberField;
            }
            set
            {
                this.UnitNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerType", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum CustomerType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Corporate = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CountryCodeField;
        
        private string PhoneExtensionField;
        
        private string PhoneNumberField;
        
        private string PhonePrefixField;
        
        private System.Nullable<Microsoft.Commerce.Proxy.AccountService.PhoneType> PhoneTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneExtension
        {
            get
            {
                return this.PhoneExtensionField;
            }
            set
            {
                this.PhoneExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhonePrefix
        {
            get
            {
                return this.PhonePrefixField;
            }
            set
            {
                this.PhonePrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Microsoft.Commerce.Proxy.AccountService.PhoneType> PhoneType
        {
            get
            {
                return this.PhoneTypeField;
            }
            set
            {
                this.PhoneTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatus", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum AccountStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Locked = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxExemptionInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class TaxExemptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CertificateNumberField;
        
        private System.Nullable<System.DateTime> DateAddedField;
        
        private System.Nullable<System.DateTime> DateReceivedField;
        
        private System.Nullable<System.DateTime> ExpDateField;
        
        private bool IsSkipVatIdValidationField;
        
        private System.Nullable<Microsoft.Commerce.Proxy.AccountService.TaxExemptionStatus> StatusField;
        
        private System.Nullable<Microsoft.Commerce.Proxy.AccountService.TaxExemptionType> TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateNumber
        {
            get
            {
                return this.CertificateNumberField;
            }
            set
            {
                this.CertificateNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateAdded
        {
            get
            {
                return this.DateAddedField;
            }
            set
            {
                this.DateAddedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateReceived
        {
            get
            {
                return this.DateReceivedField;
            }
            set
            {
                this.DateReceivedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpDate
        {
            get
            {
                return this.ExpDateField;
            }
            set
            {
                this.ExpDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSkipVatIdValidation
        {
            get
            {
                return this.IsSkipVatIdValidationField;
            }
            set
            {
                this.IsSkipVatIdValidationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Microsoft.Commerce.Proxy.AccountService.TaxExemptionStatus> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Microsoft.Commerce.Proxy.AccountService.TaxExemptionType> Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Violation", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class Violation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private int ViolationIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViolationID
        {
            get
            {
                return this.ViolationIDField;
            }
            set
            {
                this.ViolationIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapAddressResult", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class MapAddressResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> AddressMapAttemptedField;
        
        private System.Nullable<double> AddressMapConfidenceScoreField;
        
        private System.Nullable<byte> AddressMapFailureReasonField;
        
        private System.Nullable<bool> AddressMapSucceededField;
        
        private System.Nullable<bool> ManualAddressSpecifiedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AddressMapAttempted
        {
            get
            {
                return this.AddressMapAttemptedField;
            }
            set
            {
                this.AddressMapAttemptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> AddressMapConfidenceScore
        {
            get
            {
                return this.AddressMapConfidenceScoreField;
            }
            set
            {
                this.AddressMapConfidenceScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> AddressMapFailureReason
        {
            get
            {
                return this.AddressMapFailureReasonField;
            }
            set
            {
                this.AddressMapFailureReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AddressMapSucceeded
        {
            get
            {
                return this.AddressMapSucceededField;
            }
            set
            {
                this.AddressMapSucceededField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ManualAddressSpecified
        {
            get
            {
                return this.ManualAddressSpecifiedField;
            }
            set
            {
                this.ManualAddressSpecifiedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneType", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum PhoneType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Home = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Primary = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Work = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alternate = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxExemptionStatus", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum TaxExemptionStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Valid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PastDue = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxExemptionType", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum TaxExemptionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VATID = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USExempt = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanadianFederalExempt = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanadianProvinceExempt = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrazilCNPJID = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrazilCPFID = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrazilCCMID = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CanadianBothExempt = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identity", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class Identity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] IdentityPropertyField;
        
        private string IdentityTypeField;
        
        private string IdentityValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] IdentityProperty
        {
            get
            {
                return this.IdentityPropertyField;
            }
            set
            {
                this.IdentityPropertyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityType
        {
            get
            {
                return this.IdentityTypeField;
            }
            set
            {
                this.IdentityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityValue
        {
            get
            {
                return this.IdentityValueField;
            }
            set
            {
                this.IdentityValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountSearchCriteria", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class AccountSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AccountIdField;
        
        private Microsoft.Commerce.Proxy.AccountService.Identity IdentityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountId
        {
            get
            {
                return this.AccountIdField;
            }
            set
            {
                this.AccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Identity Identity
        {
            get
            {
                return this.IdentityField;
            }
            set
            {
                this.IdentityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdditionalRequiredInfo", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum AdditionalRequiredInfo : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxProfileStatus = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleAssignment", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class RoleAssignment : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Commerce.Proxy.AccountService.Identity IdentityField;
        
        private string ObjectIdField;
        
        private string RoleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Identity Identity
        {
            get
            {
                return this.IdentityField;
            }
            set
            {
                this.IdentityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectId
        {
            get
            {
                return this.ObjectIdField;
            }
            set
            {
                this.ObjectIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractResponse", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.UpdateAccountOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.GetAccountOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.AddRoleAssignmentOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.GetPermitsForObjectIdOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.CreateAccountOutput))]
    public partial class AbstractResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Microsoft.Commerce.Proxy.AccountService.AckCodeType AckField;
        
        private Microsoft.Commerce.Proxy.AccountService.ErrorType ErrorField;
        
        private bool IsSameTrackingGuidRetryField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBagField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AckCodeType Ack
        {
            get
            {
                return this.AckField;
            }
            set
            {
                this.AckField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.ErrorType Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSameTrackingGuidRetry
        {
            get
            {
                return this.IsSameTrackingGuidRetryField;
            }
            set
            {
                this.IsSameTrackingGuidRetryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class ErrorType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        private string ErrorDescriptionField;
        
        private string ErrorLongMessageField;
        
        private string ErrorShortMessageField;
        
        private Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBagField;
        
        private bool RetryableField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription
        {
            get
            {
                return this.ErrorDescriptionField;
            }
            set
            {
                this.ErrorDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorLongMessage
        {
            get
            {
                return this.ErrorLongMessageField;
            }
            set
            {
                this.ErrorLongMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorShortMessage
        {
            get
            {
                return this.ErrorShortMessageField;
            }
            set
            {
                this.ErrorShortMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Property[] PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Retryable
        {
            get
            {
                return this.RetryableField;
            }
            set
            {
                this.RetryableField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAccountOutput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class UpdateAccountOutput : Microsoft.Commerce.Proxy.AccountService.AbstractResponse
    {
        
        private Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountOutputInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountOutputInfo
        {
            get
            {
                return this.AccountOutputInfoField;
            }
            set
            {
                this.AccountOutputInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAccountOutput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class GetAccountOutput : Microsoft.Commerce.Proxy.AccountService.AbstractResponse
    {
        
        private Microsoft.Commerce.Proxy.AccountService.AccountInfo[] AccountOutputInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AccountInfo[] AccountOutputInfo
        {
            get
            {
                return this.AccountOutputInfoField;
            }
            set
            {
                this.AccountOutputInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddRoleAssignmentOutput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class AddRoleAssignmentOutput : Microsoft.Commerce.Proxy.AccountService.AbstractResponse
    {
        
        private Microsoft.Commerce.Proxy.AccountService.RoleAssignment RoleAssignmentOutputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.RoleAssignment RoleAssignmentOutput
        {
            get
            {
                return this.RoleAssignmentOutputField;
            }
            set
            {
                this.RoleAssignmentOutputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPermitsForObjectIdOutput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class GetPermitsForObjectIdOutput : Microsoft.Commerce.Proxy.AccountService.AbstractResponse
    {
        
        private Microsoft.Commerce.Proxy.AccountService.Permit[] PermitSetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.Permit[] PermitSet
        {
            get
            {
                return this.PermitSetField;
            }
            set
            {
                this.PermitSetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAccountOutput", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class CreateAccountOutput : Microsoft.Commerce.Proxy.AccountService.AbstractResponse
    {
        
        private Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountOutputInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.AccountInfo AccountOutputInfo
        {
            get
            {
                return this.AccountOutputInfoField;
            }
            set
            {
                this.AccountOutputInfoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AckCodeType", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public enum AckCodeType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RetryableFailure = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonRetryableFailure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Permit", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class Permit : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CreationTimeField;
        
        private Microsoft.Commerce.Proxy.AccountService.PermitObject ItemField;
        
        private Microsoft.Commerce.Proxy.AccountService.RoleAssignment RoleAssignmentField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationTime
        {
            get
            {
                return this.CreationTimeField;
            }
            set
            {
                this.CreationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.PermitObject Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Microsoft.Commerce.Proxy.AccountService.RoleAssignment RoleAssignment
        {
            get
            {
                return this.RoleAssignmentField;
            }
            set
            {
                this.RoleAssignmentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermitObject", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Microsoft.Commerce.Proxy.AccountService.PermitServiceInstance))]
    public partial class PermitObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string StatusField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermitServiceInstance", Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService")]
    public partial class PermitServiceInstance : Microsoft.Commerce.Proxy.AccountService.PermitObject
    {
        
        private string FriendlyNameField;
        
        private string PartnerIdField;
        
        private string PartnerNameField;
        
        private string ProvisioningErrorCodeField;
        
        private string ProvisioningStatusField;
        
        private string ServiceComponentIdField;
        
        private string ServiceComponentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this.FriendlyNameField;
            }
            set
            {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerId
        {
            get
            {
                return this.PartnerIdField;
            }
            set
            {
                this.PartnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerName
        {
            get
            {
                return this.PartnerNameField;
            }
            set
            {
                this.PartnerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvisioningErrorCode
        {
            get
            {
                return this.ProvisioningErrorCodeField;
            }
            set
            {
                this.ProvisioningErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvisioningStatus
        {
            get
            {
                return this.ProvisioningStatusField;
            }
            set
            {
                this.ProvisioningStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceComponentId
        {
            get
            {
                return this.ServiceComponentIdField;
            }
            set
            {
                this.ServiceComponentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceComponentName
        {
            get
            {
                return this.ServiceComponentNameField;
            }
            set
            {
                this.ServiceComponentNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService", ConfigurationName="Microsoft.Commerce.Proxy.AccountService.AccountService")]
    public interface AccountService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/TestConnection" +
            "", ReplyAction="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AccountService" +
            "/TestConnectionResponse")]
        string TestConnection(string inputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/CreateAccount", ReplyAction="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AccountService" +
            "/CreateAccountResponse")]
        Microsoft.Commerce.Proxy.AccountService.CreateAccountOutput CreateAccount(Microsoft.Commerce.Proxy.AccountService.CreateAccountInput createAccountInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/UpdateAccount", ReplyAction="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AccountService" +
            "/UpdateAccountResponse")]
        Microsoft.Commerce.Proxy.AccountService.UpdateAccountOutput UpdateAccount(Microsoft.Commerce.Proxy.AccountService.UpdateAccountInput updateAccountInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/GetAccount", ReplyAction="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AccountService" +
            "/GetAccountResponse")]
        Microsoft.Commerce.Proxy.AccountService.GetAccountOutput GetAccount(Microsoft.Commerce.Proxy.AccountService.GetAccountInput getAccountInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AddRoleAssignm" +
            "ent", ReplyAction="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AccountService" +
            "/AddRoleAssignmentResponse")]
        Microsoft.Commerce.Proxy.AccountService.AddRoleAssignmentOutput AddRoleAssignment(Microsoft.Commerce.Proxy.AccountService.AddRoleAssignmentInput addRoleAssignmentInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/GetPermitsForO" +
            "bjectId", ReplyAction="urn:schemas.microsoft.com/CommercePlatform/Services/AccountService/AccountService" +
            "/GetPermitsForObjectIdResponse")]
        Microsoft.Commerce.Proxy.AccountService.GetPermitsForObjectIdOutput GetPermitsForObjectId(Microsoft.Commerce.Proxy.AccountService.GetPermitsForObjectIdInput getPermitsForObjectIdInput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceChannel : Microsoft.Commerce.Proxy.AccountService.AccountService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<Microsoft.Commerce.Proxy.AccountService.AccountService>, Microsoft.Commerce.Proxy.AccountService.AccountService
    {
        
        public AccountServiceClient()
        {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string TestConnection(string inputString)
        {
            return base.Channel.TestConnection(inputString);
        }
        
        public Microsoft.Commerce.Proxy.AccountService.CreateAccountOutput CreateAccount(Microsoft.Commerce.Proxy.AccountService.CreateAccountInput createAccountInput)
        {
            return base.Channel.CreateAccount(createAccountInput);
        }
        
        public Microsoft.Commerce.Proxy.AccountService.UpdateAccountOutput UpdateAccount(Microsoft.Commerce.Proxy.AccountService.UpdateAccountInput updateAccountInput)
        {
            return base.Channel.UpdateAccount(updateAccountInput);
        }
        
        public Microsoft.Commerce.Proxy.AccountService.GetAccountOutput GetAccount(Microsoft.Commerce.Proxy.AccountService.GetAccountInput getAccountInput)
        {
            return base.Channel.GetAccount(getAccountInput);
        }
        
        public Microsoft.Commerce.Proxy.AccountService.AddRoleAssignmentOutput AddRoleAssignment(Microsoft.Commerce.Proxy.AccountService.AddRoleAssignmentInput addRoleAssignmentInput)
        {
            return base.Channel.AddRoleAssignment(addRoleAssignmentInput);
        }
        
        public Microsoft.Commerce.Proxy.AccountService.GetPermitsForObjectIdOutput GetPermitsForObjectId(Microsoft.Commerce.Proxy.AccountService.GetPermitsForObjectIdInput getPermitsForObjectIdInput)
        {
            return base.Channel.GetPermitsForObjectId(getPermitsForObjectIdInput);
        }
    }
}
